#!/bin/sh

agent="Mozilla/5.0 (Windows NT 6.1; Win64; rv:109.0) Gecko/20100101 Firefox/109.0"
lua_script="$HOME/.config/mpv/scripts/skip.lua"

die() {
    printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
    exit 1
}

update_script() {
    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/synacktraa/ani-skip/master/$1")" || die "Connection error"
    update="$(printf '%s\n' "$update" | diff -u "$2" -)"
    if [ -z "$update" ]; then
        printf "Script is up to date :)\n"
    else
        if printf '%s\n' "$update" | patch "$2" -; then
            printf "Script has been updated\n"
        else
            die "Can't update for some reason!"
        fi
    fi
}

get_skip_times() {
        [ ! -f "$lua_script" ] && die "'skip.lua' script not found!"

        name=$(printf "%s" "$1" | sed -E "s@(.+\b)( \().*@\1@")
        keyword=$(printf "%s" "$name" | sed -E 's| |%20|g')
        mal_id=$(curl -s --connect-timeout 5 -A "$agent" "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword" | jq .categories[].items[0].id)
        [ -z "$mal_id" ] && die "MyAnimeList ID not found!"

        ani_skip_metadata=$(curl -s --connect-timeout 5 -A "$agent" "https://api.aniskip.com/v1/skip-times/$mal_id/$2?types=op")
        found_status=$(printf "%s" "$ani_skip_metadata" | jq .found)
        [ "$found_status" = "false" ] && die "Skip times not found!"
        
        start_time=$(echo "$ani_skip_metadata" | jq .results[].interval.start_time)
        end_time=$(echo "$ani_skip_metadata" | jq .results[].interval.end_time)
        options="skip-start_time=$start_time,skip-end_time=$end_time"
        skip_flag="--script-opts=$options '--script=$lua_script'"
}

if [ "$#" -eq 1 ] && [ "$1" = "-U" ]; then
    update_script "ani-skip-jq" "$0"
    update_script "skip.lua" "$lua_script"
    exit 0
elif [ "$#" -ne 2 ]; then
    printf "%s [\"title\"] [ep]\n" "${0##*/}"
    exit 0
fi

get_skip_times "$1" "$2"
printf '%s' "$skip_flag"
