#!/bin/sh

get_skip_times() {
        name=$(printf "%s" "$title" | sed -E "s@(.+\b)( \().*@\1@")
        keyword=$(printf "%s" "$name" | sed -E 's| |%20|g')
        mal_id=$(curl -s "https://myanimelist.net/search/prefix.json?type=anime&keyword=$keyword" | jq .categories[].items[0].id)
        [ -z "$mal_id" ] && printf "\033[1;31mMyAnimeList ID not found!\033[0m\n" 1>&2 && return 1

        aniskip_output=$(curl -s "https://api.aniskip.com/v1/skip-times/$mal_id/$ep_no?types[]=op")
        found_status=$(printf "%s" "$aniskip_output" | jq .found)
        [ "$found_status" = "false" ] && printf "\033[1;31mSkip times not found!\033[0m\n" 1>&2 && return 1
        
        start_time=$(echo $aniskip_output | jq .results[].interval.start_time)
        end_time=$(echo $aniskip_output | jq .results[].interval.end_time)
        opts_flag="--script-opts=skip-start_time=$start_time,skip-end_time=$end_time"
        skip_flag="$opts_flag --script=~/.config/mpv/scripts/skip.lua"
}
[ "$#" -ne 2 ] && printf "%s [\"title\"] [ep]\n" "${0##*/}" && exit 1

title="$1" ep_no="$2" get_skip_times
printf "%s" "$skip_flag"
